// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08Rk-DwLRLrC0R2RrCy1FKhPg8Bx1Ick',
    appId: '1:362021637892:web:439e9020c541838bbdca51',
    messagingSenderId: '362021637892',
    projectId: 'autoresqv1',
    authDomain: 'autoresqv1.firebaseapp.com',
    storageBucket: 'autoresqv1.firebasestorage.app',
    measurementId: 'G-XT7RH8ZFGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACrFmsr86ByPlFvNGgPTusmUaO1euQQJU',
    appId: '1:362021637892:android:11868fe0bb741068bdca51',
    messagingSenderId: '362021637892',
    projectId: 'autoresqv1',
    storageBucket: 'autoresqv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJM-X9vmJQvfmb1_EvFYFCMFJ1zfgbdM',
    appId: '1:362021637892:ios:580f70dfe20932cebdca51',
    messagingSenderId: '362021637892',
    projectId: 'autoresqv1',
    storageBucket: 'autoresqv1.firebasestorage.app',
    androidClientId: '362021637892-jgkmdn9e8v4n9toh63sp8lajeft3c4o2.apps.googleusercontent.com',
    iosClientId: '362021637892-8dmhifk1ka13489n98fbqt6c7vk2tsbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoresq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJM-X9vmJQvfmb1_EvFYFCMFJ1zfgbdM',
    appId: '1:362021637892:ios:580f70dfe20932cebdca51',
    messagingSenderId: '362021637892',
    projectId: 'autoresqv1',
    storageBucket: 'autoresqv1.firebasestorage.app',
    androidClientId: '362021637892-jgkmdn9e8v4n9toh63sp8lajeft3c4o2.apps.googleusercontent.com',
    iosClientId: '362021637892-8dmhifk1ka13489n98fbqt6c7vk2tsbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoresq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA08Rk-DwLRLrC0R2RrCy1FKhPg8Bx1Ick',
    appId: '1:362021637892:web:cf412fa394d504efbdca51',
    messagingSenderId: '362021637892',
    projectId: 'autoresqv1',
    authDomain: 'autoresqv1.firebaseapp.com',
    storageBucket: 'autoresqv1.firebasestorage.app',
    measurementId: 'G-9GQGK8P4QX',
  );
}
